framework:
    notifier:
        chatter_transports:
        texter_transports:
        channel_policy:
            # use chat/slack, chat/telegram, sms/twilio or sms/nexmo
            urgent: ['mails']
            high: ['mails']
            medium: ['mails']
            low: ['mails']
        admin_recipients:
            - { email: admin@example.com }
